import * as pdfjsLib from "https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.min.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc = "https://cdn.jsdelivr.net/npm/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs";

const DB_NAME="narrador-db-v1", STORE="books", PARSER_VERSION=4;
const $=s=>document.querySelector(s);
let db;

function cleanText(text=""){return String(text).replace(/\u00ad/g,"").replace(/([A-Za-zÁÉÍÓÚÜÑáéíóúüñ])-\n([A-Za-zÁÉÍÓÚÜÑáéíóúüñ])/g,"$1$2").replace(/[ \t]+\n/g,"\n").replace(/\n{3,}/g,"\n\n").replace(/[ \t]{2,}/g," ").trim();}
function norm(s=""){return String(s).normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[“”\"'«»]/g,"").replace(/[–—−]/g,"-").replace(/\s+/g," ").replace(/\s*[.·•…]+\s*\d+\s*$/g,"").trim();}
function median(a){if(!a.length)return 0;const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2;}
function strongHeading(s=""){const t=s.trim().replace(/\s+/g," ");if(!t||t.length>140)return false;if(/^(?:(?:chapter|cap[ií]tulo|part|parte|book|libro|section|secci[oó]n)\s+(?:[ivxlcdm\d]+|[a-záéíóúüñ]+)|prologue|pr[oó]logo|epilogue|ep[ií]logo|introduction|introducci[oó]n|preface|prefacio)\b.*$/i.test(t))return true;return /^(?:[IVXLCDM]{1,12}|\d{1,3})\s*(?:[–—-]|[.:])\s*\S.{0,115}$/i.test(t);}
function stripPageNo(s=""){return s.trim().replace(/\s*[.·•…]{2,}\s*\d{1,5}\s*$/g,"").replace(/\s{2,}\d{1,5}\s*$/g,"").trim();}
function flattenOutline(items,out=[]){for(const i of items||[]){if(i?.title)out.push(String(i.title).trim());if(i?.items?.length)flattenOutline(i.items,out);}return out;}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"});};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error);});}
function allBooks(){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);});}
function putBook(b){return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).put(b);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);});}

function linesFromItems(items,viewport){const groups=[];for(const item of items){const text=String(item.str||"").trim();if(!text)continue;const tr=item.transform||[1,0,0,1,0,0],x=+tr[4]||0,y=+tr[5]||0,fs=Math.max(1,Math.abs(+tr[3]||0)||Math.hypot(+tr[0]||1,+tr[1]||0));let g=groups.find(q=>Math.abs(q.y-y)<=Math.max(2.5,fs*.22));if(!g){g={y,x0:x,x1:x+(item.width||0),sizes:[],parts:[]};groups.push(g);}g.x0=Math.min(g.x0,x);g.x1=Math.max(g.x1,x+(item.width||0));g.sizes.push(fs);g.parts.push({x,text});}groups.sort((a,b)=>b.y-a.y);return groups.map(g=>{g.parts.sort((a,b)=>a.x-b.x);const text=g.parts.map(p=>p.text).join(" ").replace(/\s+/g," ").trim(),width=Math.max(1,g.x1-g.x0);return{text,x:g.x0,y:g.y,fontSize:median(g.sizes),center:g.x0+width/2,pageWidth:viewport.width,pageHeight:viewport.height};}).filter(x=>x.text);}

async function extract(file){const pdf=await pdfjsLib.getDocument({data:await file.arrayBuffer()}).promise,outline=flattenOutline(await pdf.getOutline().catch(()=>null)),pages=[];for(let n=1;n<=pdf.numPages;n++){const status=$("#processingStatus"),bar=$("#progressBar");if(status)status.textContent=`Leyendo página ${n} de ${pdf.numPages}`;if(bar)bar.style.width=`${Math.round(n/pdf.numPages*68)}%`;const page=await pdf.getPage(n),vp=page.getViewport({scale:1}),content=await page.getTextContent(),lines=linesFromItems(content.items,vp);pages.push({number:n,lines,text:cleanText(lines.map(x=>x.text).join("\n")),medianFont:median(lines.map(x=>x.fontSize))||10});await new Promise(r=>setTimeout(r,0));}return{pages,numPages:pdf.numPages,outline};}

function inferToc(pages){const limit=Math.min(pages.length,Math.max(12,Math.ceil(pages.length*.16),24)),titles=[],tocPages=new Set();for(let p=0;p<limit;p++){let leaders=0,strong=0;const local=[];for(const l of pages[p].lines){const raw=l.text.trim();if(!raw||raw.length>160)continue;const leader=/[.·•…]{2,}\s*\d{1,5}\s*$/.test(raw)||/\s{2,}\d{1,5}\s*$/.test(raw),title=stripPageNo(raw);if(leader){leaders++;local.push(title);}if(strongHeading(title)){strong++;local.push(title);}}if(leaders>=3||(strong>=6&&p<Math.max(8,Math.ceil(pages.length*.08)))){tocPages.add(p);titles.push(...local);}}const out=[],seen=new Set();for(const t of titles){const k=norm(t);if(k&&!seen.has(k)){seen.add(k);out.push(t);}}return{titles:out,tocPages};}
function knownMatch(text,known){const k=norm(text);if(!k)return null;let best=null,score=0;for(const t of known){const q=norm(t);if(!q)continue;if(k===q)return t;if(k.length>5&&q.length>5&&(k.includes(q)||q.includes(k))){const s=Math.min(k.length,q.length)/Math.max(k.length,q.length);if(s>.8&&s>score){score=s;best=t;}}}return best;}
function headingScore(line,page,pos,known){const t=line.text.trim();if(!t||t.length>150)return{score:-99,title:t};let score=0,reasons=[],match=knownMatch(t,known);if(match){score+=7;reasons.push("índice/bookmark");}if(/^(?:(?:chapter|cap[ií]tulo|part|parte|book|libro|section|secci[oó]n)\s+(?:[ivxlcdm\d]+|[a-záéíóúüñ]+)|prologue|pr[oó]logo|epilogue|ep[ií]logo|introduction|introducci[oó]n|preface|prefacio)\b/i.test(t)){score+=6;reasons.push("patrón");}else if(/^(?:[IVXLCDM]{1,12}|\d{1,3})\s*(?:[–—-]|[.:])\s*\S/i.test(t)){score+=5;reasons.push("numeración");}else if(/^(?:[IVXLCDM]{1,8}|\d{1,3})$/i.test(t)){score+=2.5;reasons.push("número aislado");}const ratio=line.fontSize/Math.max(1,page.medianFont);if(ratio>=1.45){score+=3;reasons.push("tipografía");}else if(ratio>=1.22){score+=2;reasons.push("tipografía");}if(Math.abs(line.center-line.pageWidth/2)/(line.pageWidth/2)<.18&&t.length<100){score+=1.5;reasons.push("centrado");}if(pos<=5){score+=1.5;reasons.push("inicio de página");}else if(pos<=10)score+=.5;if(t.length<70)score+=.5;if(/^[A-ZÁÉÍÓÚÜÑ\d .,:;!?–—-]{3,80}$/.test(t))score+=.75;if(/[.!?]$/.test(t)&&t.split(/\s+/).length>10)score-=3;if(/^[\d\s]+$/.test(t))score-=4;if(/[.·•…]{2,}\s*\d{1,5}\s*$/.test(t))score-=8;return{score,title:match||t,reasons};}

function fallbackFromText(text){const lines=cleanText(text).split("\n").map(x=>x.trim()).filter(Boolean),seg=[];let cur=null,front=[];for(const line of lines){if(strongHeading(line)){if(cur){cur.text=cleanText(cur.text);seg.push(cur);}cur={title:line,text:"",startPage:null,confidence:.6};}else if(cur)cur.text+=line+"\n";else front.push(line);}if(cur){cur.text=cleanText(cur.text);seg.push(cur);}const good=seg.filter((s,i)=>s.text.length>=350||i===seg.length-1);if(good.length>=2){const f=cleanText(front.join("\n"));if(f.length>1600)good.unshift({title:"Inicio",text:f,startPage:null,confidence:.3});return good;}const whole=cleanText(text),out=[];let p=0,n=1;while(p<whole.length){let e=Math.min(p+14000,whole.length);if(e<whole.length){const b=whole.lastIndexOf("\n\n",e);if(b>p+7000)e=b;}out.push({title:`Sección ${n++}`,text:whole.slice(p,e).trim(),startPage:null,confidence:.1});p=e;}return out;}

function detect(pages,outline=[]){const toc=inferToc(pages),known=[...outline,...toc.titles],cand=[];for(let p=0;p<pages.length;p++){if(toc.tocPages.has(p))continue;for(let i=0;i<pages[p].lines.length;i++){const s=headingScore(pages[p].lines[i],pages[p],i,known);if(s.score>=6.5)cand.push({p,i,title:s.title,score:s.score,reasons:s.reasons});}}cand.sort((a,b)=>a.p-b.p||a.i-b.i||b.score-a.score);const filtered=[];for(const c of cand){const prev=filtered.at(-1);if(prev&&prev.p===c.p&&Math.abs(prev.i-c.i)<=2){if(c.score>prev.score)filtered[filtered.length-1]=c;}else filtered.push(c);}const map=new Map(filtered.map(c=>[`${c.p}:${c.i}`,c])),chapters=[];let current=null,front=[];for(let p=0;p<pages.length;p++){if(toc.tocPages.has(p))continue;for(let i=0;i<pages[p].lines.length;i++){const c=map.get(`${p}:${i}`);if(c){if(current){current.text=cleanText(current.text);if(current.text.length>=180)chapters.push(current);}current={title:c.title,text:"",startPage:p+1,confidence:Math.min(1,c.score/12),signals:c.reasons};}else{const t=pages[p].lines[i].text;if(current)current.text+=t+"\n";else front.push(t);}}if(current)current.text+="\n";else front.push("");}if(current){current.text=cleanText(current.text);if(current.text.length>=120)chapters.push(current);}const good=chapters.filter((c,i)=>c.text.length>=350||/epilogue|ep[ií]logo|prologue|pr[oó]logo/i.test(c.title)||i===chapters.length-1);if(good.length>=2){const f=cleanText(front.join("\n"));if(f.length>1600&&!toc.titles.length)good.unshift({title:"Inicio",text:f,startPage:1,confidence:.35});return good;}return fallbackFromText(pages.map(p=>p.text).join("\n\n"));}

function repairStored(book){if(!book?.chapters?.length||book.parserVersion>=PARSER_VERSION)return false;const whole=book.chapters.map(c=>`${c.title&&c.title!=="Inicio"?c.title+"\n":""}${c.text||""}`).join("\n\n"),rebuilt=fallbackFromText(whole);book.parserVersion=PARSER_VERSION;if(rebuilt.length>=3&&rebuilt.length>book.chapters.length){book.chapters=rebuilt;book.charCount=rebuilt.reduce((a,c)=>a+c.text.length,0);book.lastChapter=Math.min(book.lastChapter||0,rebuilt.length-1);book.lastSegment=0;return true;}return false;}

function showProcessing(){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$("#processingView")?.classList.add("active");window.scrollTo(0,0);}
async function importWithHybrid(file){if(!file)return;showProcessing();if($("#processingTitle"))$("#processingTitle").textContent="Analizando el libro…";if($("#processingStatus"))$("#processingStatus").textContent="Abriendo el PDF.";if($("#progressBar"))$("#progressBar").style.width="4%";try{const {pages,numPages,outline}=await extract(file);if($("#processingStatus"))$("#processingStatus").textContent="Combinando índice, bookmarks, tipografía y estructura…";if($("#progressBar"))$("#progressBar").style.width="86%";const chapters=detect(pages,outline),charCount=chapters.reduce((a,c)=>a+c.text.length,0);if(charCount<100)throw new Error("No se encontró suficiente texto.");const book={id:crypto.randomUUID?.()||String(Date.now()),title:file.name.replace(/\.pdf$/i,"").replace(/[_-]+/g," "),pages:numPages,chapters,charCount,createdAt:Date.now(),lastChapter:0,lastSegment:0,parserVersion:PARSER_VERSION};await putBook(book);if($("#progressBar"))$("#progressBar").style.width="100%";if($("#processingStatus"))$("#processingStatus").textContent=`Listo · ${chapters.length} capítulos detectados.`;setTimeout(()=>location.reload(),450);}catch(err){console.error(err);alert("No pude analizar ese PDF. Si es un escaneo, todavía necesitaremos añadir OCR.");location.reload();}}

async function syncSelector(){if(!db)return;const title=$("#playerBook")?.textContent?.trim();if(!title)return;const books=await allBooks(),book=books.find(b=>b.title===title);if(!book)return;const sel=$("#playerChapterSelect");if(!sel)return;const expected=book.chapters.length;if(sel.options.length===expected&&expected>0)return;const current=Math.max(0,Math.min(Number(sel.value)||0,expected-1));sel.innerHTML="";book.chapters.forEach((c,i)=>{const o=document.createElement("option");o.value=String(i);o.textContent=`${i+1}. ${c.title||`Capítulo ${i+1}`}`;sel.appendChild(o);});sel.value=String(current);}

await openDB();let changed=false;for(const b of await allBooks()){if(repairStored(b)){changed=true;await putBook(b);}else if((b.parserVersion||0)<PARSER_VERSION){b.parserVersion=PARSER_VERSION;await putBook(b);}}
if(changed)sessionStorage.setItem("narradorRepaired","1");

for(const id of ["#pdfInput","#pdfInput2"]){$(id)?.addEventListener("change",async e=>{e.stopImmediatePropagation();const file=e.target.files?.[0];e.target.value="";if(file)await importWithHybrid(file);},true);}

const observer=new MutationObserver(()=>syncSelector().catch(()=>{}));if($("#playerView"))observer.observe($("#playerView"),{subtree:true,childList:true,attributes:true,characterData:true});
window.addEventListener("pageshow",()=>syncSelector().catch(()=>{}));setTimeout(()=>syncSelector().catch(()=>{}),800);
