// Narrador v70 — real-device QA stabilization.
(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  let busy=false,timer=0;
  const supported=new Set(["es","en","fr","pt","it","de"]);
  function lang(){const h=String(document.documentElement.dataset.narradorLocale||"").toLowerCase().split(/[-_]/)[0];if(supported.has(h))return h;const n=String(navigator.languages?.[0]||navigator.language||"en").toLowerCase().split(/[-_]/)[0];return supported.has(n)?n:"en";}
  const D={
    read:{es:"Leer",en:"Read",fr:"Lire",pt:"Ler",it:"Leggi",de:"Lesen"},continue:{es:"Continuar escuchando",en:"Continue listening",fr:"Continuer l’écoute",pt:"Continuar ouvindo",it:"Continua ad ascoltare",de:"Weiterhören"},
    openBook:{es:"Abrir ficha del libro",en:"Open book details",fr:"Ouvrir la fiche du livre",pt:"Abrir detalhes do livro",it:"Apri dettagli libro",de:"Buchdetails öffnen"},openRead:{es:"Abrir para leer",en:"Open to read",fr:"Ouvrir pour lire",pt:"Abrir para ler",it:"Apri per leggere",de:"Zum Lesen öffnen"},editTitle:{es:"Editar título",en:"Edit title",fr:"Modifier le titre",pt:"Editar título",it:"Modifica titolo",de:"Titel bearbeiten"},editAuthor:{es:"Editar autor",en:"Edit author",fr:"Modifier l’auteur",pt:"Editar autor",it:"Modifica autore",de:"Autor bearbeiten"},deleteBook:{es:"Eliminar libro",en:"Delete book",fr:"Supprimer le livre",pt:"Excluir livro",it:"Elimina libro",de:"Buch löschen"},
    chapters:{es:"capítulos",en:"chapters",fr:"chapitres",pt:"capítulos",it:"capitoli",de:"Kapitel"},pages:{es:"páginas",en:"pages",fr:"pages",pt:"páginas",it:"pagine",de:"Seiten"},interfaceMode:{es:"Modo de interfaz",en:"Interface mode",fr:"Mode d’interface",pt:"Modo da interface",it:"Modalità interfaccia",de:"Oberflächenmodus"},currentlyLight:{es:"Actualmente: Claro",en:"Currently: Light",fr:"Actuellement : Clair",pt:"Atualmente: Claro",it:"Attualmente: Chiaro",de:"Aktuell: Hell"},currentlyDark:{es:"Actualmente: Oscuro",en:"Currently: Dark",fr:"Actuellement : Sombre",pt:"Atualmente: Escuro",it:"Attualmente: Scuro",de:"Aktuell: Dunkel"},light:{es:"Claro",en:"Light",fr:"Clair",pt:"Claro",it:"Chiaro",de:"Hell"},dark:{es:"Oscuro",en:"Dark",fr:"Sombre",pt:"Escuro",it:"Scuro",de:"Dunkel"},aiBooks:{es:"Audiolibros IA",en:"AI audiobooks",fr:"Livres audio IA",pt:"Audiolivros IA",it:"Audiolibri IA",de:"KI-Hörbücher"},generationCenter:{es:"Centro de generación",en:"Generation center",fr:"Centre de génération",pt:"Central de geração",it:"Centro di generazione",de:"Generierungszentrum"},noAiBooks:{es:"Aún no hay audiolibros IA",en:"No AI audiobooks yet",fr:"Aucun livre audio IA pour l’instant",pt:"Ainda não há audiolivros IA",it:"Nessun audiolibro IA per ora",de:"Noch keine KI-Hörbücher"},manageStorage:{es:"Gestionar almacenamiento",en:"Manage storage",fr:"Gérer le stockage",pt:"Gerenciar armazenamento",it:"Gestisci spazio",de:"Speicher verwalten"},noAiAudio:{es:"Sin audio IA guardado",en:"No AI audio stored",fr:"Aucun audio IA enregistré",pt:"Nenhum áudio IA salvo",it:"Nessun audio IA salvato",de:"Kein KI-Audio gespeichert"},enabled:{es:"Activadas",en:"Enabled",fr:"Activées",pt:"Ativadas",it:"Attive",de:"Aktiviert"},appLanguage:{es:"Idioma de la app",en:"App language",fr:"Langue de l’app",pt:"Idioma do app",it:"Lingua app",de:"App-Sprache"}
  }; const t=k=>D[k]?.[lang()]||D[k]?.en||k;
  function stripMarker(x=""){return String(x).replace(/^\s*(?:\d{1,3}|[IVXLCDM]{1,8})(?=(?:\s|[—–\-.:)]))\s*(?:[—–\-.:)]\s*)?/i,"").trim();}
  function cleanParagraph(x=""){let s=String(x).normalize("NFKC").replace(/\u00ad/g,"").replace(/[\u200B-\u200D\uFEFF]/g,"").replace(/([A-Za-zÁÉÍÓÚÜÑáéíóúüñ])-\s*\n\s*([A-Za-zÁÉÍÓÚÜÑáéíóúüñ])/g,"$1$2").replace(/\s*\n\s*/g," ").replace(/[\t ]{2,}/g," ").replace(/\s+([,.;:!?…])/g,"$1").replace(/([¿¡])\s+/g,"$1").trim();s=s.replace(/^([BCDFGHJKLMNPQRSTVWXZÑ])\s+([a-záéíóúüñ]{2,})\b/,"$1$2").replace(/\b([BCDFGHJKLMNPQRSTVWXZÑ])\s+([A-ZÁÉÍÓÚÜÑ]{2,})\b/g,"$1$2");return s;}
  function source(p){let o="";for(const n of [...p.childNodes])o+=n.nodeName==="BR"?"\n":n.textContent||"";return o;}
  function repairReader(){const r=$("#readerText");r?.querySelectorAll("p").forEach(p=>{const n=cleanParagraph(source(p));if(n&&p.textContent!==n)p.textContent=n;});const top=$("#n65ReaderTopTitle"),strong=top?.querySelector("strong"),sub=top?.querySelector("span");if(strong&&sub&&/\d/.test(strong.textContent||"")){const original=sub.dataset.n69Source||sub.dataset.n68Source||sub.textContent||"";if(!sub.dataset.n69Source)sub.dataset.n69Source=original;const fixed=stripMarker(original);if(fixed&&sub.textContent!==fixed)sub.textContent=fixed;}}
  function normalizeAuthor(x=""){return String(x).replace(/\s+/g," ").trim().replace(/^([A-Z])\.\s*([A-Z])\.\s*/,"$1. $2. ").replace(/^([A-Z])([A-Z])\.\s*/,"$1. $2. ").replace(/^([A-Z])s\.\s+/,"$1. S. ");}
  function repairAuthors(){["#n61NowPlaying .n61NowAuthor","#homeView .v18HomeAuthor","#bookAuthorLine","#library .libraryAuthor","#historyList .historyAuthor","#n62RecentSection .n62ShelfCard span"].forEach(s=>$$(s).forEach(el=>{const n=normalizeAuthor(el.textContent);if(n&&n!==el.textContent)el.textContent=n;}));}
  function replaceExact(root,a,b){if(!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT),ns=[];while(w.nextNode())ns.push(w.currentNode);for(const n of ns)if(String(n.nodeValue||"").trim()===a){const l=(n.nodeValue.match(/^\s*/)||[""])[0],r=(n.nodeValue.match(/\s*$/)||[""])[0];n.nodeValue=l+b+r;}}
  function localizeMetadata(){const ch=t("chapters"),pg=t("pages");$$("#library .bookRow p,#bookMeta,#historyList p").forEach(el=>{let s=String(el.textContent||"");s=s.replace(/(\d+)\s+(?:capítulos|chapters|chapitres|capitoli|Kapitel)\b/gi,(_,n)=>`${n} ${ch}`).replace(/(\d+)\s+(?:páginas|pages|pagine|Seiten)\b/gi,(_,n)=>`${n} ${pg}`);if(s!==el.textContent)el.textContent=s;});}
  function localizeSettings(){const root=$("#settingsView");if(!root)return;[["Modo de interfaz",t("interfaceMode")],["Interface mode",t("interfaceMode")],["Actualmente: Claro",t("currentlyLight")],["Currently: Light",t("currentlyLight")],["Actualmente: Oscuro",t("currentlyDark")],["Currently: Dark",t("currentlyDark")],["Claro",t("light")],["Light",t("light")],["Oscuro",t("dark")],["Dark",t("dark")],["Audiolibros IA",t("aiBooks")],["AI audiobooks",t("aiBooks")],["Centro de generación",t("generationCenter")],["Generation center",t("generationCenter")],["Aún no hay audiolibros IA",t("noAiBooks")],["No AI audiobooks yet",t("noAiBooks")],["Gestionar almacenamiento",t("manageStorage")],["Manage storage",t("manageStorage")],["Sin audio IA guardado",t("noAiAudio")],["No AI audio stored",t("noAiAudio")],["Activadas",t("enabled")],["Enabled",t("enabled")],["Idioma de la app",t("appLanguage")],["App language",t("appLanguage")]].forEach(([a,b])=>replaceExact(root,a,b));if(lang()==="en")$$("#settingsView .settingText span,#settingsView .settingsNote").forEach(el=>{let s=String(el.textContent||"").replace(/([\d.,]+\s*(?:KB|MB|GB))\s+usados de\s+([\d.,]+\s*(?:KB|MB|GB))\s+disponibles/i,"$1 used · $2 available").replace(/Calculando espacio…/gi,"Calculating space…").replace(/Revisando audiolibros…/gi,"Checking audiobooks…");if(s!==el.textContent)el.textContent=s;});}
  function localizeActionMenu(){const m=$("#bookActionMenu");if(!m)return;({open:"openBook",read:"openRead",title:"editTitle",author:"editAuthor",delete:"deleteBook"});Object.entries({open:"openBook",read:"openRead",title:"editTitle",author:"editAuthor",delete:"deleteBook"}).forEach(([a,k])=>{const b=m.querySelector(`[data-book-action="${a}"]`);if(b&&b.textContent!==t(k))b.textContent=t(k);});}
  function repairHome(){const hero=$("#homeFeatured");if(!hero)return;const read=hero.querySelector(".v18Open span,.n61HeroActions .v18Open span");if(read&&read.textContent!==t("read"))read.textContent=t("read");const listen=hero.querySelector(".n61HeroListen span");if(listen&&listen.textContent!==t("continue"))listen.textContent=t("continue");hero.querySelectorAll(".v18Open,.n61HeroListen").forEach(btn=>[...btn.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE&&String(n.nodeValue||"").trim()).forEach(n=>n.remove()));}
  function markMenu(){const m=$("#bookActionMenu");if(!m)return;const c=getComputedStyle(m);document.body.classList.toggle("n69BookMenuOpen",c.display!=="none"&&c.visibility!=="hidden"&&Number(c.opacity||1)!==0);}
  function fixNow(){const rw=$("#n64ReadWhile"),sp=rw?.querySelector("span");if(sp)[...rw.childNodes].filter(n=>n.nodeType===Node.TEXT_NODE&&String(n.nodeValue||"").trim()).forEach(n=>n.remove());}
  function apply(){if(busy)return;busy=true;try{document.documentElement.classList.add("n69QA","n70Stable");repairReader();repairAuthors();repairHome();localizeMetadata();localizeSettings();localizeActionMenu();fixNow();markMenu();}finally{busy=false;}}
  function schedule(ms=0){clearTimeout(timer);timer=setTimeout(apply,ms);}
  function observe(sel){const el=$(sel);if(!el||el.dataset.n70Observed==="1")return;el.dataset.n70Observed="1";new MutationObserver(()=>schedule(0)).observe(el,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:["class","style","data-n64-reader-theme","data-book-id","data-chapter"]});}
  function install(){apply();["#homeView","#homeFeatured","#readerView","#settingsView","#bookActionMenu","#libraryView","#bookView","#n61NowPlaying"].forEach(observe);document.addEventListener("click",()=>schedule(0),true);document.addEventListener("change",()=>schedule(0),true);window.addEventListener("pageshow",()=>schedule(0));window.addEventListener("focus",()=>schedule(0));document.addEventListener("visibilitychange",()=>{if(!document.hidden)schedule(0);});setTimeout(()=>{["#homeView","#homeFeatured","#readerView","#settingsView","#bookActionMenu","#libraryView","#bookView","#n61NowPlaying"].forEach(observe);apply();},250);}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
  window.__narradorUX69={apply,stripMarker,cleanParagraph};
})();